### ISSUE TITLE
Support for Linux plox

### ISSUE THREAD

**Issue by suvanbanerjee** [aditya26062003/SnakeGame#1]
```
[suvanbanerjee@elitebook-830-g5 SnakeGame]$ g++ SnakeGame.cpp -o SnakeGame
SnakeGame.cpp:2:10: fatal error: conio.h: No such file or directory
    2 | #include <conio.h>
      |          ^~~~~~~~~
compilation terminated.
```
getting this error while compiling

**Comment by rainpaw** [comment]
Although tailored for Windows, if you're operating on Linux, consider utilizing the following libraries:

#include <unistd.h> // Essential for usleep
#include <termios.h> // Necessary for kbhit and getch
#include <fcntl.h> // Required for kbhit and getch"
